CREATE TABLE utilisateurs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    date_inscription DATETIME DEFAULT CURRENT_TIMESTAMP,
    statut VARCHAR(20) DEFAULT 'client'
);

ALTER TABLE utilisateurs
  ADD COLUMN nom_societe VARCHAR(150) DEFAULT NULL,
  ADD COLUMN siret VARCHAR(30) DEFAULT NULL,
  ADD COLUMN adresse_societe VARCHAR(255) DEFAULT NULL;

  ALTER TABLE utilisateurs
  ADD COLUMN adresse VARCHAR(255) DEFAULT NULL,
  ADD COLUMN code_postal VARCHAR(20) DEFAULT NULL,
  ADD COLUMN code_postal_societe VARCHAR(20) DEFAULT NULL;